name: Build

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: npm install
        run: npm ci

      - name: build aplication
        run: npm run build

      - name: install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: run unit tests
        run: npm run test -- --watch=false --browsers=Chrome,ChromeHeadless
